import type { TraceResult } from "./types";

// Demo trace showing a MOVE token transfer execution
// This demonstrates: coin::transfer -> withdraw -> deposit flow
export const DEMO_TRACE: TraceResult = {
  success: true,
  total_gas: 847,
  steps: [
    {
      step_number: 0,
      instruction: "Call",
      module_name: "coin",
      function_name: "transfer",
      line_number: 234,
      gas_delta: 10,
      gas_total: 10,
      stack: [{ module_name: "coin", function_name: "transfer", depth: 0 }],
      locals: [
        { name: "from", var_type: "&signer", value: "0x123...abc" },
        { name: "to", var_type: "address", value: "0x456...def" },
        { name: "amount", var_type: "u64", value: 1000000 },
      ],
    },
    {
      step_number: 1,
      instruction: "MoveLoc",
      module_name: "coin",
      function_name: "transfer",
      line_number: 235,
      gas_delta: 2,
      gas_total: 12,
      stack: [{ module_name: "coin", function_name: "transfer", depth: 0 }],
      locals: [
        { name: "from", var_type: "&signer", value: "0x123...abc" },
        { name: "to", var_type: "address", value: "0x456...def" },
        { name: "amount", var_type: "u64", value: 1000000 },
      ],
    },
    {
      step_number: 2,
      instruction: "Call",
      module_name: "signer",
      function_name: "address_of",
      line_number: 236,
      gas_delta: 8,
      gas_total: 20,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "signer", function_name: "address_of", depth: 1 },
      ],
      locals: [{ name: "s", var_type: "&signer", value: "0x123...abc" }],
    },
    {
      step_number: 3,
      instruction: "Ret",
      module_name: "signer",
      function_name: "address_of",
      line_number: 45,
      gas_delta: 3,
      gas_total: 23,
      stack: [{ module_name: "coin", function_name: "transfer", depth: 0 }],
      locals: [
        { name: "from", var_type: "&signer", value: "0x123...abc" },
        { name: "to", var_type: "address", value: "0x456...def" },
        { name: "amount", var_type: "u64", value: 1000000 },
        { name: "from_addr", var_type: "address", value: "0x123...abc" },
      ],
    },
    {
      step_number: 4,
      instruction: "Call",
      module_name: "coin",
      function_name: "withdraw",
      line_number: 237,
      gas_delta: 15,
      gas_total: 38,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "withdraw", depth: 1 },
      ],
      locals: [
        { name: "account", var_type: "&signer", value: "0x123...abc" },
        { name: "amount", var_type: "u64", value: 1000000 },
      ],
    },
    {
      step_number: 5,
      instruction: "BorrowGlobal",
      module_name: "coin",
      function_name: "withdraw",
      line_number: 189,
      gas_delta: 150,
      gas_total: 188,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "withdraw", depth: 1 },
      ],
      locals: [
        { name: "account", var_type: "&signer", value: "0x123...abc" },
        { name: "amount", var_type: "u64", value: 1000000 },
        {
          name: "coin_store",
          var_type: "&mut CoinStore<AptosCoin>",
          value: "{ coin: { value: 50000000 } }",
        },
      ],
    },
    {
      step_number: 6,
      instruction: "Sub",
      module_name: "coin",
      function_name: "withdraw",
      line_number: 192,
      gas_delta: 3,
      gas_total: 191,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "withdraw", depth: 1 },
      ],
      locals: [
        { name: "account", var_type: "&signer", value: "0x123...abc" },
        { name: "amount", var_type: "u64", value: 1000000 },
        {
          name: "coin_store",
          var_type: "&mut CoinStore<AptosCoin>",
          value: "{ coin: { value: 49000000 } }",
        },
        {
          name: "withdrawn",
          var_type: "Coin<AptosCoin>",
          value: "{ value: 1000000 }",
        },
      ],
    },
    {
      step_number: 7,
      instruction: "Ret",
      module_name: "coin",
      function_name: "withdraw",
      line_number: 195,
      gas_delta: 5,
      gas_total: 196,
      stack: [{ module_name: "coin", function_name: "transfer", depth: 0 }],
      locals: [
        { name: "from", var_type: "&signer", value: "0x123...abc" },
        { name: "to", var_type: "address", value: "0x456...def" },
        { name: "amount", var_type: "u64", value: 1000000 },
        { name: "coins", var_type: "Coin<AptosCoin>", value: "{ value: 1000000 }" },
      ],
    },
    {
      step_number: 8,
      instruction: "Call",
      module_name: "coin",
      function_name: "deposit",
      line_number: 238,
      gas_delta: 12,
      gas_total: 208,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "deposit", depth: 1 },
      ],
      locals: [
        { name: "account_addr", var_type: "address", value: "0x456...def" },
        { name: "coin", var_type: "Coin<AptosCoin>", value: "{ value: 1000000 }" },
      ],
    },
    {
      step_number: 9,
      instruction: "BorrowGlobal",
      module_name: "coin",
      function_name: "deposit",
      line_number: 156,
      gas_delta: 150,
      gas_total: 358,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "deposit", depth: 1 },
      ],
      locals: [
        { name: "account_addr", var_type: "address", value: "0x456...def" },
        { name: "coin", var_type: "Coin<AptosCoin>", value: "{ value: 1000000 }" },
        {
          name: "coin_store",
          var_type: "&mut CoinStore<AptosCoin>",
          value: "{ coin: { value: 25000000 } }",
        },
      ],
    },
    {
      step_number: 10,
      instruction: "Call",
      module_name: "coin",
      function_name: "merge",
      line_number: 158,
      gas_delta: 8,
      gas_total: 366,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "deposit", depth: 1 },
        { module_name: "coin", function_name: "merge", depth: 2 },
      ],
      locals: [
        { name: "dst", var_type: "&mut Coin<AptosCoin>", value: "{ value: 25000000 }" },
        { name: "src", var_type: "Coin<AptosCoin>", value: "{ value: 1000000 }" },
      ],
    },
    {
      step_number: 11,
      instruction: "Add",
      module_name: "coin",
      function_name: "merge",
      line_number: 312,
      gas_delta: 3,
      gas_total: 369,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "deposit", depth: 1 },
        { module_name: "coin", function_name: "merge", depth: 2 },
      ],
      locals: [
        { name: "dst", var_type: "&mut Coin<AptosCoin>", value: "{ value: 26000000 }" },
        { name: "src", var_type: "Coin<AptosCoin>", value: "{ value: 0 }" },
      ],
    },
    {
      step_number: 12,
      instruction: "Ret",
      module_name: "coin",
      function_name: "merge",
      line_number: 314,
      gas_delta: 3,
      gas_total: 372,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "deposit", depth: 1 },
      ],
      locals: [
        { name: "account_addr", var_type: "address", value: "0x456...def" },
        {
          name: "coin_store",
          var_type: "&mut CoinStore<AptosCoin>",
          value: "{ coin: { value: 26000000 } }",
        },
      ],
    },
    {
      step_number: 13,
      instruction: "Call",
      module_name: "event",
      function_name: "emit_event",
      line_number: 160,
      gas_delta: 250,
      gas_total: 622,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "deposit", depth: 1 },
        { module_name: "event", function_name: "emit_event", depth: 2 },
      ],
      locals: [
        {
          name: "handle",
          var_type: "&mut EventHandle<DepositEvent>",
          value: "<handle>",
        },
        { name: "msg", var_type: "DepositEvent", value: "{ amount: 1000000 }" },
      ],
    },
    {
      step_number: 14,
      instruction: "Ret",
      module_name: "event",
      function_name: "emit_event",
      line_number: 89,
      gas_delta: 5,
      gas_total: 627,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "coin", function_name: "deposit", depth: 1 },
      ],
      locals: [],
    },
    {
      step_number: 15,
      instruction: "Ret",
      module_name: "coin",
      function_name: "deposit",
      line_number: 162,
      gas_delta: 5,
      gas_total: 632,
      stack: [{ module_name: "coin", function_name: "transfer", depth: 0 }],
      locals: [],
    },
    {
      step_number: 16,
      instruction: "Call",
      module_name: "event",
      function_name: "emit_event",
      line_number: 240,
      gas_delta: 210,
      gas_total: 842,
      stack: [
        { module_name: "coin", function_name: "transfer", depth: 0 },
        { module_name: "event", function_name: "emit_event", depth: 1 },
      ],
      locals: [
        {
          name: "handle",
          var_type: "&mut EventHandle<WithdrawEvent>",
          value: "<handle>",
        },
        { name: "msg", var_type: "WithdrawEvent", value: "{ amount: 1000000 }" },
      ],
    },
    {
      step_number: 17,
      instruction: "Ret",
      module_name: "coin",
      function_name: "transfer",
      line_number: 241,
      gas_delta: 5,
      gas_total: 847,
      stack: [],
      locals: [],
    },
  ],
};
